# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01.00.03_biome2vec.ipynb.

# %% auto 0
__all__ = ['TAG', 'DATA_DIR', 'TMP_DIR', 'SG', 'biome2vec_file', 'model_vocab_file', 'vec_file', 'taxo_ids', 'vec',
           'comm2vecs_file', 'comm2vecs_metadata_file', 'load_biome2vec', 'sentence_vectorization',
           'genus_from_edges_subgraph', 'get_terminals', 'get_mean', 'genre_to_comm2vec', 'load_mgnify_c2v']

# %% ../nbs/01.00.03_biome2vec.ipynb 3
import glob
import os
import re
import json
import pandas as pd
import shutil
import numpy as np
from tqdm import tqdm

from . import config
from . import taxonomyTree

import networkx as nx


# %% ../nbs/01.00.03_biome2vec.ipynb 5
TAG = "biome2vec"


# %% ../nbs/01.00.03_biome2vec.ipynb 6
DATA_DIR = f"{config.datadir}/{TAG}"
TMP_DIR = f"{DATA_DIR}/temp"
os.makedirs(TMP_DIR, exist_ok=True)


# %% ../nbs/01.00.03_biome2vec.ipynb 19
from gensim.models import Word2Vec


# %% ../nbs/01.00.03_biome2vec.ipynb 22
SG = 1  # 1 for skip gram


# %% ../nbs/01.00.03_biome2vec.ipynb 23
biome2vec_file = f"{DATA_DIR}/word2vec.sg_{SG}_full.model"


# %% ../nbs/01.00.03_biome2vec.ipynb 27
model_vocab_file = f"{DATA_DIR}/model_vocab.json"


# %% ../nbs/01.00.03_biome2vec.ipynb 29
with open(model_vocab_file) as h:
    model_vocab = json.load(h)


# %% ../nbs/01.00.03_biome2vec.ipynb 30
def load_biome2vec():
    biome2vec = Word2Vec.load(biome2vec_file)
    return biome2vec


# %% ../nbs/01.00.03_biome2vec.ipynb 33
vec_file = f"{biome2vec_file}.wv.vectors.npy"


# %% ../nbs/01.00.03_biome2vec.ipynb 37
taxo_ids = {x: ix for ix, x in enumerate(taxonomyTree.taxonomy_graph.nodes)}


# %% ../nbs/01.00.03_biome2vec.ipynb 38
model_vocab_file = f"{DATA_DIR}/model_vocab.json"


# %% ../nbs/01.00.03_biome2vec.ipynb 39
with open(model_vocab_file) as h:
    model_vocab = json.load(h)


# %% ../nbs/01.00.03_biome2vec.ipynb 40
vec_file = f"{biome2vec_file}.wv.vectors.npy"


# %% ../nbs/01.00.03_biome2vec.ipynb 41
vec = np.load(vec_file)


# %% ../nbs/01.00.03_biome2vec.ipynb 42
from .utils import cosine_similarity


# %% ../nbs/01.00.03_biome2vec.ipynb 43
def sentence_vectorization(terminals):
    """get mean vector from terminal nodes of subgraph (community)"""
    # tax ='Laterosporus'
    tix_ = [taxo_ids.get(tax) for tax in terminals]
    tixs = [x for x in tix_ if x != None]
    v_ixs_ = [model_vocab.get(str(tix)) for tix in tixs]
    v_ixs = [x for x in v_ixs_ if x != None]
    _t = [vec[v_ix] for v_ix in v_ixs]

    # _t = [x for x in terminals if x in embs]
    mean = np.mean(_t, axis=0)
    return mean


# %% ../nbs/01.00.03_biome2vec.ipynb 45
def genus_from_edges_subgraph(edges: list):  # # List of edges of the taxonomy subgraph
    """Function to extract genra from a list of edges of the taxonomy_tree.
    tipically the output of `baseData.tax_annotations_from_file`
    """
    _nodes = {node for edge in edges for node in edge}
    genra_nodes = {
        x.split("__")[-1].split()[0]
        for x in _nodes
        if x.startswith("g__") or len(x.split()) > 1
    }
    return genra_nodes


# %% ../nbs/01.00.03_biome2vec.ipynb 46
def get_terminals(edges: list):  # List of edges of the taxonomy subgraph
    "get leaves of subgraph"
    H = nx.DiGraph()
    H.add_edges_from([x for x in edges if x[0] != x[1]])
    terminal = [x for x in H.nodes() if H.out_degree(x) == 0 and H.in_degree(x) == 1]
    terminal = [x for x in terminal if len(x.split()) == 1]
    return terminal


# %% ../nbs/01.00.03_biome2vec.ipynb 47
def get_mean(f):
    taxo_terminals = {}
    with open(f) as h:
        dct = json.load(h)

    for k, edges in dct.items():
        terminal = get_terminals(edges)
        taxo_terminals[k] = terminal
    return taxo_terminals


# %% ../nbs/01.00.03_biome2vec.ipynb 48
def genre_to_comm2vec(genres_set):
    genres_in_vocab_vecs = [
        vec[model_vocab.get(str(taxo_ids.get(x, None)), None)]
        for x in genres_set
        if model_vocab.get(str(taxo_ids.get(x, None)), None) != None
    ]
    c2v = np.mean(genres_in_vocab_vecs, axis=0)
    return c2v
    # genres_in_vocab = {taxo_ids[x] for x in genres_set if x in model_vocab.get(str(taxo_ids.get(x,None)),None) !=None }


# %% ../nbs/01.00.03_biome2vec.ipynb 59
comm2vecs_file = f"{DATA_DIR}/comm2vecs.h5"
comm2vecs_metadata_file = f"{DATA_DIR}/comm2vecs_metadata.tsv"


# %% ../nbs/01.00.03_biome2vec.ipynb 61
def load_mgnify_c2v():
    __comm2vecs = pd.read_hdf(comm2vecs_file, key="df")
    _comm2vecs_metadata = pd.read_csv(
        comm2vecs_metadata_file, sep="\t", index_col="SAMPLE_ID"
    )
    return __comm2vecs, _comm2vecs_metadata

