# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00.0.0_config.ipynb.

# %% auto 0
__all__ = ['module_name', 'is_notebook', 'basedir', 'datadir', 'find_basedir']

# %% ../nbs/00.0.0_config.ipynb 2
from os import path, makedirs
import importlib.util


# %% ../nbs/00.0.0_config.ipynb 3
module_name = "trapiche"


# %% ../nbs/00.0.0_config.ipynb 4
is_notebook = False
try:
    is_notebook = get_ipython().__class__.__name__
except:
    None


# %% ../nbs/00.0.0_config.ipynb 5
def find_basedir(module_name):
    spec = importlib.util.find_spec(module_name)
    if spec is None or spec.origin is None:
        raise ImportError(f"Module {module_name} not found")
    basedir = path.abspath(path.dirname(spec.origin))
    return basedir

# %% ../nbs/00.0.0_config.ipynb 6
# if is_notebook == False:
    # basedir = path.abspath(path.dirname(__file__))
# else:
    # basedir = path.abspath(path.join("..", module_name))
basedir = find_basedir(module_name)


# %% ../nbs/00.0.0_config.ipynb 7
datadir = path.join(basedir, "data")
makedirs(datadir, exist_ok=True)

