# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00.0.0_config.ipynb.

# %% auto 0
__all__ = ['module_name', 'is_notebook', 'datadir']

# %% ../nbs/00.0.0_config.ipynb 2
from os import path,makedirs

# %% ../nbs/00.0.0_config.ipynb 3
module_name='trapiche'

# %% ../nbs/00.0.0_config.ipynb 4
is_notebook = False
try:
    is_notebook = get_ipython().__class__.__name__
except:
    None

# %% ../nbs/00.0.0_config.ipynb 5
if is_notebook == False:
    basedir =  path.abspath(path.join(path.dirname(__file__),module_name))
else:
    basedir =  path.abspath(path.join("..",module_name))

# %% ../nbs/00.0.0_config.ipynb 6
datadir = path.join(basedir,'data')
makedirs(datadir,exist_ok=True)
